spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        storage_engine: innodb
    show-sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

naver:
  url:
    search:
      local: https://openapi.naver.com/v1/search/local.json
      image: https://openapi.naver.com/v1/search/image
  client:
    id: QL0yLyXpTNGl8wERPmUp
    secret: SGRA5GhpO4